### ISSUE TITLE
Make sure to include OVR_CAPI_Keys.h in the generator 

### ISSUE THREAD

**Issue by jherico** [cmbruns/pyovr#1]
In order to get constants like the version number as well as the keys for fetching the IPD and height from the SDK, you should include `OVR_CAPI_Keys.h` as one of the files during ctypes generation.

**Comment by cmbruns** [comment]
Fixed in revision 52874c8ee459014dbc2c32df32bab0e7b26ff7fc
Like I did with other identifiers, the constants are like "ovr.DEFAULT_EYE_RELIEF_DIAL", where the C constant was "OVR_DEFAULT_EYE_RELIEF_DIAL". That is, I like to use the "ovr." module name wherever there was an initial OVR or ovr or ovr_ or OVR_
